version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      github-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      python-dependencies:
        patterns:
          - '*'
