# Label for changes to GitHub Actions workflows
ci:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - ".github/lint-plugins/*"
              - ".github/workflows/*"
              - ".pre-commit-config.yaml"
              - "dprint.json"
              - ".editorconfig"

# Label for changes to the cfsite package
cfsite:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "packages/cfsite/**/*"

# Label for documentation changes
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "docs/**/*"
              - "README.md"
              - "CONTRIBUTING.md"

scripts:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "scripts/**/*"
