backend:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'packages/cfsite/src/**/*'
              - 'packages/cfsite/**/*.ts'
              - 'packages/cfsite/.wrangler/**/*'

cfsite:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'packages/cfsite/**/*'

chore:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '.editorconfig'
              - '.gitignore'
              - 'dprint.json'
              - '.pre-commit-config.yaml'
              - '.github/lint-plugins/*'

ci:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '.github/workflows/*'
              - '.wrangler/**/*'

config:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '.*'

dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'yarn.lock'
              - 'npm-shrinkwrap.json'

development:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'dprint.json'
              - '.editorconfig'
              - '.pre-commit-config.yaml'
              - '.github/lint-plugins/*'

documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'README.md'
              - 'CONTRIBUTING.md'
              - 'docs/**/*'

frontend:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'public/**/*'

infra:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '.github/**/*'
              - '.vscode/*'

root:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '*'

scripts:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'scripts/**/*'

tests:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '**/test/**/*'
              - '**/*.test.ts'
              - '**/*.spec.ts'
