ci:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - ".github/workflows/*"

cfsite:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "packages/cfsite/**/*"

development:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "dprint.json"
              - ".editorconfig"
              - ".pre-commit-config.yaml"
              - ".github/lint-plugins/*"

documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "docs/**/*"
              - "README.md"
              - "CONTRIBUTING.md"

scripts:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "scripts/**/*"
