version = 1

# Configure the analyzers to be used. Each analyzer gets its own [[analyzers]] block.
[[analyzers]]
name = "javascript"
enabled = true
[analyzers.meta]
eslint_config = ".github/linters/eslint.config.mjs"
[[analyzers]]
name = "python"
enabled = true
[analyzers.meta]
runtime_version = "3.12" # Specify the Python runtime version for the analyzer.

[[analyzers]]
name = "secrets"
enabled = true
# [[analyzers]]
# name = "test-coverage"
# enabled = true
