comment:
  layout: 'diff, flags, files'
  behavior: default
  require_changes: false
  require_base: false
  hide_project_coverage: false
coverage:
  range: 50...75
  round: down
  precision: 2
  status:
    project:
      default: false
      cfsite:
        flags:
          - cfsite
        paths:
          - 'packages/cfsite'
        target: 70%
        threshold: 1%
      app:
        flags:
          - app
        paths:
          - '!packages/cfsite'
        target: auto
        threshold: 1%
