comment:
  layout: 'diff, flags, files'
  behavior: default
  require_changes: false
coverage:
  range: 50...75
  round: down
  precision: 2
  status:
    project:
      default: false
      tests:
        paths:
          - 'packages/cfsite'
        target: 70%
        threshold: 1%
      app:
        paths:
          - '!packages/cfsite'
        target: auto
        threshold: 1%
