comment:
  layout: 'diff, flags, files'
  behavior: default
coverage:
  status:
    project:
      default: false
      tests:
        paths: 'packages/cfsite'
        target: 55%
        threshold: 1%
      app:
        paths: '!packages/cfsite'
        target: auto
        threshold: 1%
