# https://github.com/DavidAnson/markdownlint?tab=readme-ov-file#rules--aliases

# MD013 line-length - Line length
MD013:
  line_length: 530

# MD025 single-title/single-h1 - Multiple top-level headings in the same document
MD025: false

# MD033 no-inline-html - Inline HTML
MD033: false

# MD041 first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false

# MD051 link-fragments - Link fragments should be valid
MD051: false
