# https://yamllint.readthedocs.io/en/stable/
extends: default
rules:
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  line-length: disable
  truthy: false
