name = "brisbane-social-chess"
description = "Welcome to the source code repository for the Brisbane Social Chess website."
license = "MIT"
homepage = "https://github.com/brisbanesocialchess/brisbanesocialchess.github.io"

min_version = "0.17.0"

demo = "https://github.com/brisbanesocialchess/brisbanesocialchess.github.io"

[author]
name = "Max Base"
homepage = "https://..."

[extra]
override_serif_with_sans = false
theme_switcher = true
default_theme = ""
skin = ""
stylesheets = []
remote_repository_git_platform = "auto"  # Defaults to "auto".
remote_repository_branch = "main"  # Defaults to "main".
show_remote_changes = true  # Defaults to true.
show_remote_source = true  # Defaults to true.
copy_button = true
code_block_name_links = false
force_codeblock_ltr = true
show_author = false
show_reading_time = true
show_date = true
post_listing_date = "date"
post_listing_index_reversed = false
