---
name: 👷🏾‍♂️ CI - Build Eleventy on PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: 🈸 Build
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 24

      - name: ⚙️ Install dependencies
        run: npm install

      - name: 🏗️ Build site
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -d "./_deploy" ]; then
            echo "_deploy folder missing — build failed"
            exit 1
          fi
