name: ✅ Dprint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dprint:
    name: 👣 Run dprint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Cache dprint
        id: cache-dprint
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/dprint
            ~/.dprint/bin
          key: ${{ runner.os }}-dprint-${{ hashFiles('dprint.json') }}
          restore-keys: |
            ${{ runner.os }}-dprint-

      - name: 🏗️ Install dprint
        if: steps.cache-dprint.outputs.cache-hit != 'true'
        run: curl -fsSL https://dprint.dev/install.sh | sh

      - name: Add dprint to PATH
        run: echo "$HOME/.dprint/bin" >> "$GITHUB_PATH"

      - name: 🏃🏻‍♂️‍➡️ Run dprint check
        run: dprint check --allow-no-files
