name: 🥇 First Interaction

permissions:
  issues: write
  pull-requests: write

on:
  pull_request_target: # zizmorlinter:disable dangerous-triggers
    types: [opened, reopened]
  issues:
    types: [opened]

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@753c925c8d1ac6fede23781875376600628d9b5d
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          issue_message: |
            Thanks for opening this issue! We appreciate your contribution.
          pr_message: |
            Thanks for your first pull request! We appreciate your contribution.
