name: 🥇 First Interaction

permissions:
  issues: write
  pull-requests: write

on: # zizmorlinter:disable dangerous-triggers
  pull_request_target:
    types: [opened, reopened]
  issues:
    types: [opened]

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          issue_message: |
            Thanks for opening this issue! We appreciate your contribution.
          pr_message: |
            Thanks for your first pull request! We appreciate your contribution.
