name: Dprint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dprint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dprint
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/dprint
            ~/.dprint/bin
          key: ${{ runner.os }}-dprint-${{ hashFiles('dprint.json') }}
          restore-keys: |
            ${{ runner.os }}-dprint-

      - name: Install dprint
        if: steps.cache-dprint.outputs.cache-hit != 'true'
        run: curl -fsSL https://dprint.dev/install.sh | sh

      - name: Add dprint to PATH
        run: echo "$HOME/.dprint/bin" >> $GITHUB_PATH

      - name: Run dprint check
        run: dprint check
