name: Build Pelican site on PR

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Check if pelicanconf.py exists
        id: check_pelicanconf
        run: |
          if [ -f pelicanconf.py ]; then
            echo "file_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "file_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install dependencies
        if: steps.check_pelicanconf.outputs.file_exists == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pelican markdown

      - name: Build Pelican site
        if: steps.check_pelicanconf.outputs.file_exists == 'true'
        run: pelican content -o output -s pelicanconf.py

      - name: Upload artifact (optional)
        if: steps.check_pelicanconf.outputs.file_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: pelican-site
          path: output/

      - name: Deploy to GitHub Pages
        if: github.event_name == 'pull_request' && steps.check_pelicanconf.outputs.file_exists == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages-pr-${{ github.event.number }}
